### ISSUE TITLE
metadata-map usage

### ISSUE THREAD

**Issue by kmandalas** [barrycommins/prometheus-eureka-spring-boot-demo#1]
Hello, 

Can you please explain why the following configuration is needed? its usage? Thanks.

```
 metadata-map:
      metrics.path: ${management.context-path:/actuator}/${endpoints.prometheus.id:prometheus}
      health.path: ${management.context-path:/actuator}/${endpoints.health.id:health}
      management.context-path: ${management.context-path:/actuator}
```
